# common
spring:
  profiles:
    active: local
  application:
    name: gateway
  messages:
    basename: messages
  cloud:
    gateway:
      default-filters:
        - name: LogFilter
      routes:
        - id: route_auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/**
          filters:
            - name: RewritePath
              args:
                regexp: /auth/?(?<segment>.*)
                replacement: /$\{segment}
            - name: RequestSize
              args:
                maxSize: 5000000
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 100
                  burstCapacity: 100
                  requestedTokens: 1
                key-resolver: "#{@myKeyResolver}"
      redis-rate-limiter:
        include-headers: false
      httpclient:
        connect-timeout: 10000
        response-timeout: 10s
      x-forwarded:
        for-enabled: false
        host-enabled: false
        port-enabled: false
        proto-enabled: false
        prefix-enabled: false
  data:
    redis:
      time-to-live: 3600000
  r2dbc:
    max-idle-time: 60000
    max-lifetime: 180000
    max-create-connection-time: 2s
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
hibernate:
  cache:
    use-second-level-cache: true
service:
  jwt:
    access-expiration: 3600000
    skip-path-regex: .*/public/.*, ^/login$, ^/token$

---
# local
server:
  port: 8080
eureka:
  instance:
    hostname: localhost
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      #      password: ENC(vs80g6g8RPF/BSJqw0ONpT7rvXgeri0SMZ/PszCK0O4V384HLZPICWdp) # redis-password
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/example?serverTimezone=Asia/Seoul
    username: postgres
    password: 1234
    properties:
      schema: temp
    pool:
      initial-size: 5
      max-size: 10
  security:
    user:
      password: 1234
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:9000'
          jws-algorithms: 'RS512'
          jwk-set-uri: 'http://localhost:9000/.well-known/jwks.json'
#          public-key-location: classpath:my-public-key.pub
service:
  jwt:
    private-key: keys/jwt-private_pkcs8.pem
    public-key: keys/jwt-public.pem
  api:
    auth:
      base-path: 'lb://AUTH-SERVICE/auth'

---
# dev
spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      #      password: ENC(vs80g6g8RPF/BSJqw0ONpT7rvXgeri0SMZ/PszCK0O4V384HLZPICWdp) # redis-password
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?serverTimezone=Asia/Seoul
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    properties:
      schema: ${POSTGRES_SCHEMA}
    pool:
      initial-size: 5
      max-size: 10
  security:
    user:
      password: 1234
server:
  port: ${GATEWAY_PORT}
eureka:
  instance:
    hostname: ${DISCOVERY_HOST}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${DISCOVERY_PORT}/eureka
service:
  jwt:
    private-key: keys/jwt-private_pkcs8.pem
    public-key: keys/jwt-public.pem
  api:
    auth:
      base-path: http://localhost:8082/auth # lb://AUTH-SERVICE/auth
