# local
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      #      password: ENC(vs80g6g8RPF/BSJqw0ONpT7rvXgeri0SMZ/PszCK0O4V384HLZPICWdp) # redis-password
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/my_db?serverTimezone=Asia/Seoul
    username: postgres
    password: 1234
    properties:
      schema: temp
    pool:
      initial-size: 5
      max-size: 10
  security:
    user:
      password: 1234
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth
          jws-algorithms: 'RS512'
          jwk-set-uri: http://localhost:8080/auth/.well-known/jwks.json
#          public-key-location: classpath:my-public-key.pub

server:
  port: 8080

eureka:
  instance:
    hostname: localhost
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

---
# dev
spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: 0
      #      password: ENC(vs80g6g8RPF/BSJqw0ONpT7rvXgeri0SMZ/PszCK0O4V384HLZPICWdp) # redis-password
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?serverTimezone=Asia/Seoul
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    properties:
      schema: ${POSTGRES_SCHEMA}
    pool:
      initial-size: 5
      max-size: 10
  security:
    user:
      password: 1234
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URI}
          jws-algorithms: 'RS512'
          jwk-set-uri: ${AUTH_ISSUER_URI}/.well-known/jwks.json

server:
  port: ${GATEWAY_PORT}

eureka:
  instance:
    hostname: ${DISCOVERY_HOST}
  client:
    service-url:
      defaultZone: ${DISCOVERY_BASE_URL}/eureka/

---
# common
spring:
  application:
    name: gateway
  messages:
    basename: messages
  cloud:
    gateway:
      default-filters:
        - name: LogFilter
      routes:
        - id: route_auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/?(?<segment>.*), /$\{segment}
            - name: RequestSize
              args:
                maxSize: 5000000
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 100
                  burstCapacity: 100
                  requestedTokens: 1
                key-resolver: "#{@myKeyResolver}"
      redis-rate-limiter:
        include-headers: false
      httpclient:
        connect-timeout: 10000
        response-timeout: 10s
      x-forwarded:
        for-enabled: false
        host-enabled: false
        port-enabled: false
        proto-enabled: false
        prefix-enabled: false
  data:
    redis:
      time-to-live: 3600000
  r2dbc:
    max-idle-time: 60000
    max-lifetime: 180000
    max-create-connection-time: 2s
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
