server:
  port: 8011
spring:
  application:
    name: client
  security:
    oauth2:
      client:
        registration:
          my-registration-id:
            provider: my-provider-id
            client-id: client_id_1
            client-secret: client_secret_1
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          my-provider-id:
            authorization-uri: http://localhost:9000/oauth2/authorization
            token-uri: http://localhost:9000/oauth2/token
            jwk-set-uri: http://localhost:9000/.well-known/jwks.json
            issuer-uri: http://localhost:9000
            user-info-uri: http://localhost:9000/oauth2/userinfo
            user-name-attribute: sub

logging:
  level:
    root: debug