# common
spring:
  application:
    name: discovery
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
  server:
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: false
    fetch-registry: false

---
# local
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
# dev
spring:
  config:
    activate:
      on-profile: dev
server:
  port: ${DISCOVERY_PORT}
eureka:
  instance:
    hostname: ${DISCOVERY_HOST}
  client:
    service-url:
      defaultZone: ${DISCOVERY_BASE_URL}/eureka/
